### ISSUE TITLE
Starting with functional connectivity matrices

### ISSUE THREAD

**Issue by amsinha9** [kisungyou/papers#1]
Great toolbox! In SPDtoolbox, how does spd_initialize work if our input matrices are subject-specific functional connectivity N x N covariance matrices? We don't start with 3d matrices.

**Comment by kisungyou** [comment]
Hi, all spd_* functions are designed to work with multiple SPD matrices. Therefore, if you have subject-specific FC matrices, please provide your data as of the form described on the help page. If this doesn't answer your question well, please let me know since I'm not aware of what context you are considering for usage of the codes.

**Comment by amsinha9** [comment]
I'm looking to do group-level analysis on the functional connectivity matrices (i.e. patients vs. controls). So how would I load and structure the subject and group SPD matrices using spd_initialize to do subsequent analysis using the methods in the toolbox?

**Comment by kisungyou** [comment]
Okay, I get it. Looking at the [example code](https://github.com/kyoustat/papers/blob/master/SPDtoolbox/example_eqdist.m) would help, which requires you to fill in the 3d array. Here is how. Suppose you have `n` matrices of size (p,p). Then, define a 3d array object, say `X = zeros(p,p,n)` and you fill each slice as `X(:,:,i) = your matrix` where `i` is an iterator.

**Comment by amsinha9** [comment]
Within example_eqdist.m, what do lines 12 and 13 refer to as "objects"? I went back through your paper to find the reference, but it isn't clear how we define number of objects per class (which I'm assuming "class" = group?).

**Comment by kisungyou** [comment]
Object refers to a SPD matrix (not in the context of object-oriented programming at all). The code is an example where I used arbitrary numbers of cardinalities for each class(= group of known labels). For example, you have two sets of FC matrices, `n1` of normal and `n2` of control. Then you can _test_ equality of distributions using eqdist.
