### ISSUE TITLE
threshold in spd_initialize

### ISSUE THREAD

**Issue by amsinha9** [kisungyou/papers#2]
How do we determine a suitable threshold for spd_initialize?

**Comment by amsinha9** [comment]
Also, I used spd_initialize on two groups of covariance matrices to generate the structs as shown below and try to use spd_eqtest:

```
data1 = spd_initialize(control_3darray);
data2 = spd_initialize(patient_3darray);

ntest = 100;
recx  = zeros(1,ntest);
reci  = zeros(1,ntest);

for i=1:ntest
    recx(i) = spd_eqtest(data1, data2);
    reci(i) = spd_eqtest(data1, data2, "intrinsic");  
end
```
but get the error:
Warning: Principal matrix logarithm is not defined for A with nonpositive real
eigenvalues. A non-principal matrix logarithm is returned. 
> In logm (line 78)
  In spdaux_dist (line 10)
  In spd_pdist (line 35)
  In spd_eqtest (line 45)

the error seems to be in reci(i) = spd_eqtest(data1, data2, "intrinsic"). Is there a function to make matrices spd if there are negative real eigenvalues?

**Comment by kisungyou** [comment]
There is no best way to determine threshold, it is your job. Also, that is
warning, not error - meaning your object is rank deficient though you can
still get something from numerical approximation. If it were error, it
would have stopped.

**Comment by amsinha9** [comment]
Thank you for the clarification. The size of final objects for testing are 379x379x88 and 379x379x88, in which I'm running spd_eqtest(data1, data2). Given the size of the data, is it reasonable that even with ntest=10, it will take a while to run?

**Comment by kisungyou** [comment]
Yes, since operations need to be performed each of your matrix.

**Comment by amsinha9** [comment]
Thank you for the clarification and help, I appreciate it!
